"""PDF Risk Report generation + Cloud Storage upload."""

import datetime
import io
import logging
import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from persistence.models import ClauseRecord, SessionRecord

logger = logging.getLogger("para.pdf")

SEVERITY_COLORS = {
    "RED": colors.HexColor("#ef4444"),
    "YELLOW": colors.HexColor("#f59e0b"),
    "GREEN": colors.HexColor("#22c55e"),
}


class PdfReportService:
    def __init__(self, bucket_name: str | None = None):
        self._bucket_name = bucket_name
        self._gcs_client = None

    def _get_gcs_bucket(self):
        if not self._bucket_name:
            return None
        if self._gcs_client is None:
            from google.cloud import storage
            self._gcs_client = storage.Client()
        return self._gcs_client.bucket(self._bucket_name)

    def generate_pdf(
        self,
        session: SessionRecord,
        clauses: list[ClauseRecord],
        risk_score: int,
        risk_grade: str,
    ) -> io.BytesIO:
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=20, spaceAfter=6)
        sub_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=10, textColor=colors.grey)
        section_style = ParagraphStyle("Section", parent=styles["Heading2"], fontSize=14, spaceBefore=16, spaceAfter=6)
        body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=11, leading=16)
        disclaimer_style = ParagraphStyle("Disc", parent=styles["Normal"], fontSize=8, textColor=colors.grey, leading=12)

        elements = []

        # Header
        elements.append(Paragraph("Contract Risk Report", title_style))
        ts = datetime.datetime.fromtimestamp(session.started_at).strftime("%B %d, %Y at %I:%M %p")
        elements.append(Paragraph(f"Session: {session.id} &bull; {ts}", sub_style))
        elements.append(Spacer(1, 12))

        # Risk score summary
        red_count = sum(1 for c in clauses if c.severity == "RED")
        yellow_count = sum(1 for c in clauses if c.severity == "YELLOW")
        green_count = sum(1 for c in clauses if c.severity == "GREEN")

        summary_data = [
            ["Risk Score", "Grade", "Red Flags", "Cautions", "Clear"],
            [str(risk_score), risk_grade, str(red_count), str(yellow_count), str(green_count)],
        ]
        summary_table = Table(summary_data, colWidths=[1.2 * inch] * 5)
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e2030")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTSIZE", (0, 1), (-1, 1), 16),
            ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
            ("TEXTCOLOR", (2, 1), (2, 1), SEVERITY_COLORS["RED"]),
            ("TEXTCOLOR", (3, 1), (3, 1), SEVERITY_COLORS["YELLOW"]),
            ("TEXTCOLOR", (4, 1), (4, 1), SEVERITY_COLORS["GREEN"]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 16))

        # Clauses by severity
        for severity, label in [("RED", "Red Flags"), ("YELLOW", "Cautions"), ("GREEN", "Clear")]:
            sev_clauses = [c for c in clauses if c.severity == severity]
            if not sev_clauses:
                continue
            color = SEVERITY_COLORS[severity]
            elements.append(Paragraph(f'<font color="#{color.hexval()[2:]}">{label}</font> ({len(sev_clauses)})', section_style))
            for c in sev_clauses:
                elements.append(Paragraph(f'<b>{c.clause_type}</b>', body_style))
                if c.raw_text:
                    elements.append(Paragraph(f'<i>"{c.raw_text[:200]}"</i>', body_style))
                elements.append(Paragraph(c.analysis, body_style))
                elements.append(Spacer(1, 8))

        # Disclaimer
        elements.append(Spacer(1, 24))
        elements.append(Paragraph(
            "This report was generated by Para, an AI legal assistant. "
            "It does not constitute legal advice. Always consult a qualified attorney before making legal decisions.",
            disclaimer_style,
        ))

        doc.build(elements)
        buf.seek(0)
        return buf

    async def generate_and_upload(
        self,
        session: SessionRecord,
        clauses: list[ClauseRecord],
        risk_score: int,
        risk_grade: str,
    ) -> dict:
        """Generate PDF and optionally upload to GCS. Returns file info."""
        pdf_buf = self.generate_pdf(session, clauses, risk_score, risk_grade)
        filename = f"risk-report-{session.id}.pdf"

        bucket = self._get_gcs_bucket()
        if bucket:
            blob_name = f"reports/{session.id}/{filename}"
            blob = bucket.blob(blob_name)
            blob.upload_from_file(pdf_buf, content_type="application/pdf", rewind=True)
            url = blob.generate_signed_url(
                expiration=datetime.timedelta(hours=1),
                method="GET",
            )
            logger.info("PDF uploaded to GCS: %s", blob_name)
            return {"url": url, "filename": filename, "storage": "gcs"}

        # Local dev: save to data/reports/
        reports_dir = os.path.join(os.environ.get("DATA_DIR", "data"), "reports")
        os.makedirs(reports_dir, exist_ok=True)
        local_path = os.path.join(reports_dir, filename)
        with open(local_path, "wb") as f:
            f.write(pdf_buf.getvalue())
        logger.info("PDF saved locally: %s", local_path)
        return {"path": f"/api/reports/{filename}", "filename": filename, "storage": "local"}
